# permissions for end users to edit dmgs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: dmg-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: olivetree
    app.kubernetes.io/part-of: olivetree
    app.kubernetes.io/managed-by: kustomize
  name: dmg-editor-role
rules:
- apiGroups:
  - daos.hpe.com
  resources:
  - dmgs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - daos.hpe.com
  resources:
  - dmgs/status
  verbs:
  - get
